### ISSUE TITLE
Docker tag version and Pip install version

### ISSUE THREAD

**Issue by j7an** [b3vis/docker-borgmatic#14]
Could we specify the Borg version as a variable in the Dockerfile? Then install that specific version in the pip install command? The latest Borg/Borgmatic version may not be the most stable or to some, considered the "safest" as shown in this issue: [1.1.8 has BAD gpg signature on pypi.org](https://github.com/borgbackup/borg/issues/4213)

This will allow each build to be tagged and pushed to Docker Hub with the same Borg/Borgmatic version as the pip install. With tagged versions should allow an app like [watchtower](https://github.com/v2tec/watchtower) to automatically install the latest version if a user decides to use the latest tag or just get a notification.

**Comment by b3vis** [comment]
Sure submit a PR and I’ll review it

**Comment by toastie89** [comment]
Updated to latest version #17

**Comment by toastie89** [comment]
Having multiple versions on Docker Hub would be great. I've seen this, but never tried it out. Is this something what needs to be set in the Dockerfile, in Dockerhub or even elsewhere?

> This will allow each build to be tagged and pushed to Docker Hub with the same Borg/Borgmatic version as the pip install. With tagged versions should allow an app like [watchtower](https://github.com/v2tec/watchtower) to automatically install the latest version if a user decides to use the latest tag or just get a notification.
