### ISSUE TITLE
Multistage-Build

### ISSUE THREAD

**Issue by toastie89** [b3vis/docker-borgmatic#19]
Hi! I've [modified the Dockerfile](https://github.com/toastie89/docker-borgmatic/blob/patch-4/Dockerfile) to build borg and borgmatic in an intermediate container so the final image will not have all the build dependencies using the [multistage-build](https://docs.docker.com/develop/develop-images/multistage-build/) mechanism.

From the builder I copy the complete `site-packages` folder and borg related python scripts from `/usr/bin`.
```
COPY --from=builder /usr/lib/python3.6/site-packages /usr/lib/python3.6/
COPY --from=builder /usr/bin/*borg* /usr/bin/
```
Not sure if this is the best approach to move things around or there is a better way in the python world? Any thoughts? May I raise a pull request?

**Comment by b3vis** [comment]
have you tested backing up and restoring using this method? only other comment I have is it may be best to copy the binaries specifically than using wildcards

`COPY --from=builder /usr/bin/*borg* /usr/bin/`

I have some other images I've written using multistage-build as it does result in a cleaner/smaller image so no problems moving to this. Just to add though I've stopped using this image myself for my personal backups and have started using restic which offers pretty much exactly the same feature parity plus the ability to use online services for repos.

If you can test this and submit a PR I'll merge it

**Comment by toastie89** [comment]
I've tested several backups and restores and the multi-stage version works fine. PR opened :-)

**Comment by b3vis** [comment]
Thank you for all your efforts @toastie89 - Apologies for the late reply I haven't had a chance to review this until now.

Thanks,
b3vis
