### ISSUE TITLE
crontab example should not include user

### ISSUE THREAD

**Issue by witten** [b3vis/docker-borgmatic#2]
When I try using a crontab similar to the example in the README, I get an error that indicates crond is trying to run a command that starts with the name of the user (root), instead of interpreting it as the user to run the command as. Here's the contents of crond.log when that occurs:

```
/ # cat /config/crond.log
crond: crond (busybox 1.26.2) started, log level 8
crond: USER root pid   7 cmd root PATH=$PATH:/usr/bin /usr/bin/borgmatic --config /config/config.yaml
/bin/sh: root: not found
```
I believe that's because this crontab is being interpreted as a "personal" crontab instead of a system-wide one, and thus the user is assumed to be the current user.

And here's the content of my crontab.txt:

```
0 4 * * * root PATH=$PATH:/usr/bin /usr/bin/borgmatic --config /config/config.yaml
```

However, when I remove "root" from the crontab and try again, cron runs just fine, as evidenced by no more errors in the log file, and a new archive showing up in my repository.

**Comment by b3vis** [comment]
thanks for the info, I'll remove the user specification of root from the examples
