### ISSUE TITLE
Simplify to defaults?

### ISSUE THREAD

**Issue by toastie89** [b3vis/docker-borgmatic#22]
Hi! I would like to use **default locations** for config and cache and update the readme and Dockerfile accordingly. This way the image would be more consistent with borgmatic documentation. 

New set of volumes would be:
```
  - /mnt/source          # backup source
  - /mnt/repository      # backup destination
  - /root/.config/borg   # config and keyfiles
  - /root/.cache/borg    # checksums used for deduplication
  - /root/.ssh           # ssh key for remotebackup
  - /etc/borgmatic.d     # borgmatic config file(s) + crontab.txt
```

What do you think about?

**Comment by toastie89** [comment]
I've prepared the needed changes over here:
https://github.com/toastie89/docker-borgmatic/tree/patch-2

**Comment by toastie89** [comment]
Added an example borgmatic config.yml to the patch which should work for simple use cases without many modifications and ease testing.

**Comment by toastie89** [comment]
Added a pull request :-)

**Comment by b3vis** [comment]
Do we need to remove line 32 from the Dockerfile if you've specified them as volumes?

`&& mkdir /config /cache /source /repository /root/.ssh`

**Comment by toastie89** [comment]
Good point, this part should be obsolete now. I'll run another test without it and then add another commit to the pull request.

**Comment by toastie89** [comment]
I've updated the pull request :-)

**Comment by b3vis** [comment]
Perfect, again thank you for your patience in my slowness to respond. IRL responsibilities mean I don't have much free time at the moment
