### ISSUE TITLE
Allow non-root users on host to access borgmatic repository??

### ISSUE THREAD

**Issue by avamk** [b3vis/docker-borgmatic#27]
Huge thanks to @b3vis for creating this wonderful container!

I successfully followed the instructions in this repository to set up a Docker borgmatic set up to back up files from a source on the Docker *host* (e.g. `/path/to/files`) to a repository also on the host (e.g. `/path/to/repo`).

The problem is, even if I `chown`/`chmod` `/path/to/repo` to a certain user and group, this container changes the permission of the repository to root with root-exclusive read/write access.

What I want is the ability to *at least* read this repository from the Docker *host*, and ideally read and write access.

One thing I tried is use the `--user` argument with user and group IDs (e.g. 123:456) from the Docker host like this when creating and running this container: `docker run --user 123:456 [other arguments go here...]` However, this fails because apparently crontab inside the container "requires suid privileges".

So, how can I set up this borgmatic container so that non-root users can access its repository?? As a relative newcomer to Docker I'd appreciate any specific suggestions, thank you!

**Comment by MarkJonas** [comment]
I think this is not a Docker configuration but a *borgmatic* / *Borg* configuration.

Have you considered setting the `umask` appropriately? You should have the following in your *borgmatic* configuration file.

```
    # Umask to be used for borg create. Defaults to 0077.
    #umask: 0077
```

So the default setting will prohibit all access rights for group and others.

I haven't tried it but I have a strong gut feeling that you need to `chmod` and `chown` your repo directory and configure the `umask` appropriately.

- https://borgbackup.readthedocs.io/en/stable/usage/notes.html?highlight=umask#umask
- https://torsion.org/borgmatic/docs/reference/configuration/
- https://en.wikipedia.org/wiki/Umask

**Comment by avamk** [comment]
Thanks @MarkJonas for your suggestion. I tried the following inside my borgmatic config.yaml file:

```
storage:
    umask: 0000
```

Then I started a brand new borgmatic container to test the config.yaml. I also made sure that after the repository is initiated, but before the first backup is made, I `sudo chmod -R 777` to the entire repository (I tried this from both within and outside of the container). *However*, after the first backup is created, the permissions of the new and modified files in the repository are changed to 700 again for user root:root. I also tried to `sudo chown` first to my desired non-root user, but that didn't help. Whenever a new archive is created, the ownership changes back to root with 700 permissions.

The config.yaml is definitely read by borgmatic inside the container, because my other configurations are respected and applied.

Anything else I'm missing? Thanks!

**Comment by b3vis** [comment]
Hi

It could be redesigned so that the borgmatic cron is started as a user which gets created with UID and GID from envars. I currently don't have time to complete this myself but welcome a PR if you do manage to code it. If not I can try and get around to it at some point.

**Comment by toastie89** [comment]
Hi avamk, die you try to change the user in your docker run command?
https://docs.docker.com/engine/reference/run/#user

Assuming you bind-mount directories into the container, UIDs in the container are the same as on the host. So you should define the corresponding UID of the data on the host you plan to backup.

**Comment by avamk** [comment]
Hi @toastie89, thanks for the suggestion. I think I've already tried to change the user in my `docker run` command as seen in my original post, quoted here:

> One thing I tried is use the --user argument with user and group IDs (e.g. 123:456) from the Docker host like this when creating and running this container: docker run --user 123:456 [other arguments go here...] However, this fails because apparently crontab inside the container "requires suid privileges".

Or were you suggesting something else?

Also, I mounted my directories into the container by defining volumes. Is "bind-mount directories" another way of doing this? Does it make a difference? Thanks!!

**Comment by b3vis** [comment]
Currently the container image is written that everything runs as root so anything you backup doesn't get permission errors. I understand this isn't the best solution but at the time of writing I couldn't get it to happily backup my server (including /etc et al) without using root.

Is it a massive issue in that you just have to chown your repo if you want to access the repo outside of this container? I think I could re-write the image so it runs cron etc as another user which is created on container start but this isn't something I need right now so will be on the back burner. Feel free to submit a PR if you manage to change it yourself though.

**Comment by toastie89** [comment]
@avamk, installing the package busybox-suid should fix the issue with crond / crontab as regular user. Workarounds for writing to /dev/stdout are described here: https://github.com/moby/moby/issues/31243

In case you prepare a PR, please leave the option to run as root open to allow backup of full machines.

**Comment by toastie89** [comment]
Changing entry.sh as follow would allow to set the UID for running borgmatic in the environment variable $uid.  Review and testing welcome :-)
```
#!/bin/sh
# If $uid environment variable is set, create corresponding user to run borgmatic
if [ $uid -gt 99 ] && [ $uid -lt 65535 ]
then runas=dummy; adduser -D -u $uid dummy; else runas=root; fi
# Import your cron file
/usr/bin/crontab -u $runas /etc/borgmatic.d/crontab.txt
# Start cron
/usr/sbin/crond -f -L /dev/stdout
```

**Comment by kaustubh105** [comment]
@toastie89 Is your approach better than what Linuxserver does? https://github.com/linuxserver/docker-baseimage-alpine/blob/master/root/etc/cont-init.d/10-adduser

Trying to see which method might be better off considering home dir creation etc

**Comment by toastie89** [comment]
> Trying to see which method might be better off considering home dir creation etc
Is there something you miss from my proposal above?

**Comment by kaustubh105** [comment]
The Linuxserver method lets you set the id, and runs as that user (so I can run it as my local user instead of root). I think that would ensure that the files are owned by $USER:$USER instead of root:root, which was the issue @avamk had as well

**Comment by grantbevis** [comment]
@kaustubh105 raise a PR with your proposed changes and @toastie89 and I will review.

it was decided to backup as root so it’s possible to backup an entire file system if you wish. I suppose if you could make it a envar then it’s not a bad thing

**Comment by mmartinortiz** [comment]
Hi,

I landed into this closed issue while looking for a way to run the image with a given UID and GID, or using the [user](https://docs.docker.com/reference/compose-file/services/#user) attribute in docker compose.

In my use case, I run borgmatic as a service that runs along another service. Borgmatic takes care of backing up the config file of this service. The only drawback is that all the files created by borgmatic (cache, repos...) are owned by root.

If I use the `user` attribute, the logs will show this:

```bash
borgmatic  | /package/admin/s6-overlay/libexec/preinit: info: /run belongs to uid 0 instead of 1000 - fixing it
borgmatic  | s6-rc-compile: fatal: unable to opendir /etc/s6-overlay/s6-rc.d: Permission denied
```

Trying to exec bash, shows the following messages:

```bash
❯ docker compose exec borgmatic bash
Error loading shared library libreadline.so.8: Permission denied (needed by /bin/bash)
Error relocating /bin/bash: unstifle_history: symbol not found
```

Is it possible to run the borgmatic service, or at least the borgmatic process when the backups are done, using a specific user?

**Comment by ilanbiala** [comment]
Yeah I see the same thing as @mmartinortiz. @grantbevis could you please reopen this issue? This isn't completed, and it made it harder to find that this is a known issue.

Also, is there somewhere in the docs that mention how to work with the fact that files are backed up as `root` and are not readable by default?

**Comment by grantbevis** [comment]
Feel free to open a PR

**Comment by ilanbiala** [comment]
A PR would be separate from reopening the issue, and starting a new issue would just lose this history.

**Comment by modem7** [comment]
This is a fundamental characteristic of how Borg repositories work — Borg sets repository permissions deliberately to restrict access, as the repository contains backup data that should not be casually readable.

Running borgmatic as a non-root user inside the container isn't straightforward — S6 and crond require root, and borgmatic needs to read all source files (including those owned by other users on the host), which typically requires root anyway.

For users who only have Docker available on the host, there are a few options:

**Option 1: Access the repository from within the container**

This is the simplest approach — since borgmatic runs as root inside the container, you have full access to the repository without any permission issues:

```console
# List archives
docker exec -it borgmatic borgmatic list

# Mount an archive for browsing (see docker-compose.restore.yml)
`docker compose -f docker-compose.yml -f docker-compose.restore.yml run borgmatic`
```

**Option 2: Run borg directly inside the container**

```console
docker exec -it borgmatic borg list /mnt/borg-repository
docker exec -it borgmatic borg info /mnt/borg-repository
```

**Option 3: Change repository permissions after initialisation**

If you need host-side access, add your host user to a group and chown the repository to that group after repo-create. Set the setgid bit so new files inherit the group:

```bash
sudo chown -R root:mygroup /path/to/repo
sudo chmod -R g+rX /path/to/repo
sudo chmod g+s /path/to/repo
```

Note this only affects host-side read access — Borg itself will continue to function normally inside the container.

**Option 4: Use a remote repository**

If the repository lives on a remote server (BorgBase, rsync.net, your own SSH server), host-side permission issues don't apply at all, and this is the recommended setup for most users.

Running the container as a non-root user is not supported.
