### ISSUE TITLE
Correct way of using this image and creating borg repo?

### ISSUE THREAD

**Issue by thepenguinthatwants** [b3vis/docker-borgmatic#29]
Hi!

I am kinda new with borg. So I was wondering whats the correct procedure with starting and using a borg repository.

in the docker-compose.yml file I changed the volume into
` - '$PWD/repository:/mnt/repository' `

Is this the correct procedure to create a repo?
```
docker exec -it borgmatic sh
cd /mnt/repository/
borg init -e test.borg
```

Also in the config.yml I added 
repositories:
`        - /mnt/repository `

does it need to be         

`- /mnt/repository/test.borg`

 instead?

**Comment by b3vis** [comment]
Yo,

I'd probably reccomend not using `$PWD/repo` if using compose and would set out a specific path. While what you're doing isn't wrong I'd just suggest you split it out and kept your compose files somewhere away from your repo data. Then you can use git to keep track of your compose files too.

That's correct yeah you can create the Borg repo using either Borg from another machine natively or via the container.

From the command you've given it would be `/mnt/repository/test.borg` - though I'd recommend just creating the repo as `/mnt/repository` keeps it simpler unless you wish to have multiple repos under the `/mnt/repository` directory but then you'll loose the dedupe/compression benefits if you run the same machines into multiple repos. 

Lots to think about :)

Cheers,
b3vis

**Comment by thepenguinthatwants** [comment]
Hiya!

Thanks for the reply. I am using the $PWD/repo just for testing. Later on going to make it more reasonable manner.

True this way its load better unless multiple repo.

`borg init -e none /mnt/repository`

Seems like something is wrong with my config.yaml

```
location:
    # List of source directories to backup. Globs are expanded.
    source_directories:
        - /home/Docker
    repositories:
        - /mnt/repository
 

```

As the logs contains:


```
borgmatic    | ["Key 'exclude_patterns' was not defined. Path: '/storage'"]
borgmatic    | Errors found but will not raise exception...
borgmatic    | /etc/borgmatic.d/config.yaml: Error parsing configuration file
borgmatic    | An error occurred while parsing a configuration file at /etc/borgmatic.d/config.yaml:
borgmatic    | Key 'exclude_patterns' was not defined. Path: '/storage'
borgmatic    | 
borgmatic    | Need some help? https://torsion.org/borgmatic/#issues
```

I guess its because the repositories had to be - /mnt/repository/test.borg ? But then it doesnt really make sense to "exclude_patterns" -error.

**Comment by b3vis** [comment]
I think you need to have `exclude_patterns` defined as a key in the yaml

**Comment by thepenguinthatwants** [comment]
Hiya!

seems like the exclude_patterns wasnt needed  I had just had some typo.

You earlier mentioned

> you wish to have multiple repos under the /mnt/repository directory but then you'll loose the dedupe/compression benefits if you run the same machines into multiple repos.

How come? If I have multiple repos why would it spoil the dedupe/compression?

**Comment by b3vis** [comment]
Because if you backup

Machine A to Repo A
Machine B to Repo B 

but both machines have 80% of the same data you will store that 80% twice if you are using multiple local repos.

If you backup Machines A/B to repo A which is local and both to Repo B which is remote then each machine will benefit from the dedupe algorithm because the Repo already has that data stored.

Hope that makes sense
