### ISSUE TITLE
crond log to stdout

### ISSUE THREAD

**Issue by witten** [b3vis/docker-borgmatic#3]
It's common practice with Docker containers to log to stdout, so container logs can be seen with the "docker logs" command, and if desired, logs can be collected from all the relevant containers and centralized. More on that at https://docs.docker.com/engine/admin/logging/overview/

It looks like right now, the crond invocation is logging to a file in the `/config` volume:

```
/usr/sbin/crond -f -L /config/crond.log
```

My suggestion would be to change that to log to stdout, both so that Docker can collect the logs, but also to keep logs out of the `/config` directory. For instance, that volume can't be read-only as long as it's doing double-duty as a log volume. Here's the change:

```
/usr/sbin/crond -f -L /dev/stdout
```

I tried running that variant manually, and confirmed that logs indeed go to stdout. However, I didn't try to rebuild the container image with this change or confirm that "docker logs" works as expected.

**Comment by b3vis** [comment]
Thanks for this, I've made this change on entry.sh and have pushed the changes to GitHub which will trigger a rebuild on the Docker Hub, pull the new image and double check for me please.

**Comment by witten** [comment]
Confirmed that it works, and logs are available with "docker logs" now. Thanks for making this change!
