### ISSUE TITLE
Update Readme at dockerhub

### ISSUE THREAD

**Issue by Hofer-Julian** [b3vis/docker-borgmatic#30]
Hey, great work!

Just one small request: please update the readme at dockerhub to the one at github as it seems to be more up to date :)

**Comment by b3vis** [comment]
Hey, 

Thanks for the kind words, I've just updated the hub readme :)

Kind regards,
b3vis

**Comment by Hofer-Julian** [comment]
Thank you!

Looking forward to trying it out soon :)

**Comment by b3vis** [comment]
shout if you need any help!
