### ISSUE TITLE
PostgreSQL dump hooks support

### ISSUE THREAD

**Issue by witten** [b3vis/docker-borgmatic#37]
borgmatic 1.4.0 (just released) includes support for [hooks to dump PostgreSQL databases](https://torsion.org/borgmatic/docs/how-to/backup-your-databases/) and include those dumps in your backups. I'm not sure if you want to expand scope of your Docker container, but if you do want to support this feature, you could install PostgreSQL's pg_dump/pg_dumpall/pg_restore in your image. In Alpine Linux, that's in the `postgresql-client` package.

Note that there may be plans to support [other databases](https://projects.torsion.org/witten/borgmatic/issues/228) as well, which would expand scope even further.

**Comment by b3vis** [comment]
Hi witten,

Thank you for the heads up, I will definitely look to expand the scope of the image to encompass this new feature.

Thanks
b3vis

**Comment by b3vis** [comment]
Closed due to merging @witten 's PR #38
