### ISSUE TITLE
Mount to restore not possible - Error loading shared library libfuse.so.2

### ISSUE THREAD

**Issue by rustikus** [b3vis/docker-borgmatic#39]
Hi,
thanks for preparing a ready to go docker image. Unfortunately I have a problem if I try to restore some files. I accessed the docker image via

`docker-compose -f docker-compose.yml -f docker-compose.restore.yml run borgmatic`

I created a mount point and tried to mount the restore folder but received the following error message:

`borg mount not available: loading FUSE support failed [ImportError: Error loading shared library libfuse.so.2: No such file or directory (needed by /usr/lib/python3.7/llfuse.cpython-37m-x86_64-linux-gnu.so)]`

Not sure if there is a library mismatch or I just missed something.

Thanks!

**Comment by toastie89** [comment]
Hi, I can confirm the same error message here. Installing the package `fuse` fixes the issue. Will take a closer look later on.

**Comment by b3vis** [comment]
@toastie89 fixed with #40 closing
