### ISSUE TITLE
base|msmtp|ntfy images

### ISSUE THREAD

**Issue by toastie89** [b3vis/docker-borgmatic#42]
The `MAILTO=""` in crontab apparently suppresses output in the docker log. I would therefore suggest to comment it out by default. Any opinions? @pr0totyp

(When running `docker logs borgmatic` it says `sendmail: no recipients found`.)

**Comment by pr0totyp** [comment]
Yes commenting it out seems then a good solution.

**Comment by toastie89** [comment]
When putting `MAILTO=backup@example.com` all cron output is sent via e-mail. Is this the intended behavior? @pr0totyp I guess you would only like to see when backup failed and still have the output in the docker log?

**Comment by pr0totyp** [comment]
Ja this is the idea of the MAILTO variable. In my setup i just pipe stout to /dev/null and stderr to stdout to get only errors via mail.

For sending only stderr via mail and still get stdout into docker log I would ether use a shell script like mentioned in your blog post or pipe stderr to sendmail.

With the current setting everything is possible and just a matter of configuration. Maybe we need a wiki page with different setups for sending output via mail or docker log.

**Comment by toastie89** [comment]
Added PR #43 to to comment out mailto to get back Docker logs

**Comment by toastie89** [comment]
I belief that log analysis and sending notification about failure should happen outside the Docker container to avoid bloating the image and make it more difficult to use and maintain (more configuration, side effects, security, documentation). For me it feels wrong having msmtp in the image.

**Comment by pr0totyp** [comment]
Then you have to parse the whole container output. Just getting a mail if the cronjob fails seems for me more convenient. The increase in size and complexity seems very small for me.

**Comment by toastie89** [comment]
Borgmatic itself has hooks [[1]](https://torsion.org/borgmatic/docs/how-to/add-preparation-and-cleanup-steps-to-backups/) [[2]](https://torsion.org/borgmatic/docs/how-to/inspect-your-backups/) which could become handy to run external scripts/programs for notification. Those scripts could be bind-mounted to avoid bloating this docker image and open the path for other means of notification, e.g. a Prometheus exporter notification via xmpp. Any opinions about this idea?

**Comment by aaronblair** [comment]
I struggled with this oddity a bit myself when setting things up. The PR #43 is a definite improvement. If possible, I would suggest going with the hooks option for sending out logs as it's much more clear what is happening and leave the cron logs intact. This leaves it up to the user to decide when to receive email (always on completion, only on fail, etc).

**Comment by pr0totyp** [comment]
If sending mails via cron or the borgmatic hooks the user can decided by them self with the current state. But having a running miminal mta in the container is a great feature though a lot of people still use mail for error reporting!

**Comment by toastie89** [comment]
I would suggest to remove ssmtp and bind-mount a simple python script which can be executed from a hook to send mail. The script and possibly others for e.g. xmpp or prometheus could be part of the borgmatic repository. Form mail specifically the required python library [smtplib](https://docs.python.org/3/library/smtplib.html) is even part of the image. Something like below should do the trick, what do you think about?
```
#!/usr/bin/env python3
import smtplib, sys
s = smtplib.SMTP(host='mail.example.com', port=587)
s.starttls()
s.login('username', 'password')
s.sendmail('backup@exampe.com','johndoe@example.com',sys.argv[1])
```

**Comment by pr0totyp** [comment]
Replacing packages with self written script is for my only an option if there is no package available and the chances to make mistakes are high. There was a reason somebody took the effort of writing and maintaining a package like we use now. Replacing it with a 6 lines long script doesn't seem reliable for my production environments.

Before you merged my pull request I had my fork available on docker hub and a lot of people were using it with the mail extension. So there is definitely a need.

I am happy with the solution we have and in my opinion its not bloaty. If you like move the MAILTTO var and config files from the repo to wiki and we putt everything in a separate wiki page. The script creating the `/etc/msmtprc` could also be replaced with mounted config file but this will destroy the running setups from people already using it. But the msmtp package and symlink should stay.

**Comment by toastie89** [comment]
I've updated the script to make it working with the currently defined environment variables, taking as first argument the e-mail subject and as second the e-mail body.

```
#!/usr/bin/env python3

import smtplib, sys, os
from email.mime.text import MIMEText

msg = MIMEText(sys.argv[2])
msg['Subject'] = sys.argv[1]
msg['From'] = os.environ['MAIL_FROM']
msg['To'] = os.environ['MAILTO']

s = smtplib.SMTP(host=os.environ['MAIL_RELAY_HOST'], port=os.environ['MAIL_PORT'])
s.starttls()
s.login(os.environ['MAIL_USER'], os.environ['MAIL_PASSWORD'])
s.sendmail(os.environ['MAIL_FROM'], os.environ['MAILTO'], msg.as_string())
s.quit()
```

A [borg error hook](https://torsion.org/borgmatic/docs/how-to/monitor-your-backups/#error-hooks) could look like follow to get the error message in the subject and the output of the failed command in the body of the e-mail.
```
hooks:
    on_error:
        - send-message.py "{error}" "{output}"
```

@pr0totyp, [smtplib](https://docs.python.org/3/library/smtplib.html) is part of the [python standard library](https://docs.python.org/3/library/index.html) and not something I come up with.

**Comment by b3vis** [comment]
All, apologies for the radio silence IRL responsibilities have been taking all my free time. I will hopefully set some time aside to review all of this week. 

Off the top of my head I would prefer stdout to get logged to docker logs and then users of this image use the website pre and post commands to send emails. I also have a personal feature request that I want to implement which is to have [ntfy](https://github.com/dschep/ntfy) so we can send notifications from borgmatic to many services (including email I think)

Regards,
b3vis

**Comment by toastie89** [comment]
ntfy looks quite universal and promising when it comes to notifications, I will need to give it a try next couple of days.
Especially I'm interested to get some meta data via messaging, e.g. increase/decrease in number of files and volume of backup.

It would be nice if it could run in a separate container and listen to hooks from borgmatic
and possible other processes, e.g. DB dumps or other backup solutions such as restic.

**Comment by b3vis** [comment]
@toastie89 I've merged #43 thanks for that, I'd like to include ntfy in the image which is what I'm going to work on next

**Comment by toastie89** [comment]
> [...] I'd like to include ntfy in the image which is what I'm going to work on next
@b3vis, what do you think about having a stable base image with borgmatic and the cron setup while deriving specific image with different flavours of monitoring (e.g. msmtp, ntfy, Prometheus, ...)?

**Comment by b3vis** [comment]
@toastie89 I'm not sure how we'd architect that but that does sound very cool. I toyed with the idea of having something like an envar of INSTALL_NTFY=true and then when the container starts entry.sh will install ntfy but annoyingly using the two stage build method we'd need a load of dependancies in the main container to have stuff install on the fly.

Still something to explore! I've just pushed a update to the Dockerfile to install ntfy and updated the release v1.1.10-1.4.21 to have this too

**Comment by toastie89** [comment]
@b3vis, I was thinking about to keep a simple Dockerfile with borgmatic and have separate Dockerfiles for the different flavors of notifications. Those separate images start with 'FROM b3vis/borgmatic'. This we could share/maintain a stable baseimage together and specialize in terms of notifications. In terms of contribution this helps as well as one don't need to think about all the dependencies of the notification part. What do you think about?

**Comment by b3vis** [comment]
That’s not a bad shout to be honest as we could have other branches on this repo for the ntfy image which I can then have the Docker hub auto build from the branch so

b3vis/borgmatic:v1.1.10-1.4.21 is vanilla with no email/ntfy et al

b3vis/borgmatic:v1.1.10-1.4.21-ntfy is as you say
Dockerfile:

FROM alpine:$version AS builder
pip install ntfy etc etc

FROM b3vis/borgmatic:v1.1.10-1.4.21
COPY from builder ntfy binaries etc

I should be able to still do a multistage build again to keep the image sizes small 👌🏽

I will investigate this and let you know 🤘🏼

**Comment by toastie89** [comment]
@b3vis , sounds great! If there is something I can help with, let me know :-)

**Comment by b3vis** [comment]
@toastie89 please see https://github.com/b3vis/docker-borgmatic/tree/ntfy

I've also configured Docker hub to build a image tagged `v1.1.10-1.4.21-ntfy` from this branch.

I'm not 100% convinced using branches is the correct way to do this and think possibly another repo but then it's not under the single image with different tags... I will play with this setup...

Feel free to split and remove email from the master branch and submit a PR :)

**Comment by toastie89** [comment]
@b3vis I've just checked what options Docker hub offers and found the build rule setting for build context. This would allow to keep everything in one branch and separate the notification flavours into folders. What do you think about?

The structure could look like follow:
```
docker-borgmatic/
├── base
│   ├── data
│   │   └── borgmatic.d
│   │       ├── config.yml
│   │       └── crontab.txt            # without mailto
│   ├── docker-compose.restore.yml     
│   ├── docker-compose.yml
│   ├── Dockerfile
│   ├── entry.sh      
├── msmtp
│   ├── data
│   │   └── borgmatic.d
│   │       ├── config.yml             # same as in base
│   │       └── crontab.txt            # with mailto
│   │       └── msmtprc.sh
│   ├── docker-compose.override.yml    # specifics
│   ├── docker-compose.yml             # same as in base
│   ├── Dockerfile                     # FROM b3vis/borgmatic:${VERSION}
│   ├── entry.sh                       # starting msmtp
│   └── README.md                      # describing specifics
├── ntfy
│   ├── data
│   │   └── borgmatic.d
│   │       ├── config.yml             # with the ntfy example
│   │       └── crontab.txt            # without mailto
│   ├── docker-compose.override.yml    # specifics
│   ├── docker-compose.yml             # same as in base
│   ├── Dockerfile                     # FROM b3vis/borgmatic:${VERSION}
│   ├── entry.sh                       # same as in base
│   └── README.md                      # describing specifics
└── README.md     
```

**Comment by toastie89** [comment]
@b3vis, I've created a fork with the changes described above over here:
https://github.com/toastie89/docker-borgmatic
Would you accept a pull request, possibly at first into a separate branch?

**Comment by b3vis** [comment]
Hey @toastie89 looks good but isn’t this going to disturb the main base image? I think the msmtprc.sh needs to be included in the image instead of the data file. Prepare a PR and we can discuss and review

**Comment by toastie89** [comment]
@b3vis, for building the main image the build context would need to be set to /base.
msmtprc.sh is only necessary in the msmtp image.
