### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by toastie89** [b3vis/docker-borgmatic#45]
Hi docker-borgmatic users out there!

I've just realised that Docker grants read-write access to a  read-only mounted directory when a sub-folder was bind-mounted read-write. My setup looks like follow:
```
srv/                 --> mounted read-only as $VOLUME_SOURCE
├── guests           --> this disk is a backup source
├── magnetic         --> this disk is a backup source
└── magnetic-backup  --> this disk is a backup target
                         and mounted read-write as $VOLUME_TARGET
```

```
[...]
    volumes:
      - ${VOLUME_SOURCE}:/mnt/source:ro           # backup source
      - ${VOLUME_TARGET}:/mnt/borg-repository     # backup target
[...]
```

In terms of backup this is miserable as the source should be read-only while the target should be read-write. The solution is to bind-mount `guests`and `magnetic` individually which is not possible with the current `docker-compose.yml` and `.env` file as only one backup-source can be defined.

I've defined now the bind-mounds in `.env` in one variable like `[/srv/guest:/mnt/source/guest:ro, /srv/magnetic:/mnt/source/magnetic:ro, /srv/magnetic-backup:/mnt/borg-repository:rw, ...]` and only refer to this variable in the `docker-compose.yml` volume declariation. This solution is not very nice in terms of readability. Has someone else more than one backup source as well? How do you deal with it?

**Comment by MarkJonas** [comment]
I use separate volumes for each backup source. Good to know that there is one more reason why I do that. :smiley:

**Comment by toastie89** [comment]
@MarkJonas, thanks for your reply. Do you use the vanilla docker-compse.yml from the repo? If so, how does your .env look like?

**Comment by MarkJonas** [comment]
I wish I was using docker-compose. I use this image on a Synology DiskStation. Thus I have to configure the container using the graphical front-end.

Yes, I know that I could also use the Docker command line tools doing an ssh to the DiskStation. But then I must open the graphical front-end anymore. Or else it will do things you do not want it to do. So I decided to stay on "the path of the righteous man". Still it would be nice to combine the power of both ... :smiley_cat:

**Comment by toastie89** [comment]
Apparently my situation described is not that common, so let's close this issue for now.
