### ISSUE TITLE
/bin/sh: can't open '/etc/borgmatic.d/msmtprc.sh': No such file or directory

### ISSUE THREAD

**Issue by d2dyno** [b3vis/docker-borgmatic#46]
Didn't change any config from what I was using before, and now get this message at each startup of the container:
`/bin/sh: can't open '/etc/borgmatic.d/msmtprc.sh': No such file or directory`

**Comment by b3vis** [comment]
Hi there,

Have you recently updated the image your container is based from and recreated the container?

I'd reccomend using the latest release tag: v1.1.10-1.4.21

so `docker pull b3vis/borgmatic:v1.1.10-1.4.21` and then use this image to create your container.

Looking through this release code I can see the msmtprc.sh is listed, if you re-create your container and then `docker exec -it ls /etc/borgmatic.d/msmtprc.sh` what output do you get?

https://github.com/b3vis/docker-borgmatic/blob/v1.1.10-1.4.21/data/borgmatic.d/msmtprc.sh

**Comment by b3vis** [comment]
Also you should have mounted a path to your host for /etc/borgmatic.d - have you deleted this file from the mapped folder on your host?

**Comment by toastie89** [comment]
@d2dyno, did you possibly upgrade from an earlier version of the image? msmtp has been added not too long ago.

**Comment by krzysztof-magosa** [comment]
Documentation states that either you configure environment variables like `MAIL_FROM` *OR* you mount custom `msmtprc`. It does not say that you need to copy `msmtprc.sh` from this repository and provide it externally to container.

In my opinion it should be part of container itself, because otherwise what's the benefit from using environment variables.

**Comment by krzysztof-magosa** [comment]
```
❯ docker run -d b3vis/borgmatic:v1.1.10-1.4.21
7db868f291cc336b1bbb9d81f587d25d3f0bed19a26c110943b9bc9f99a429dc

❯ docker exec 7db868f291cc336b1bbb9d81f587d25d3f0bed19a26c110943b9bc9f99a429dc ls /etc/borgmatic.d/msmtprc.sh
ls: /etc/borgmatic.d/msmtprc.sh: No such file or directory
```
