### ISSUE TITLE
Update borgmatic to 1.5.1

### ISSUE THREAD

**Issue by gbrks** [b3vis/docker-borgmatic#49]
There are a few improvements in borgmatic v1.5.0 and v1.5.1 that would be ideal:

- #277: Customize Healthchecks log level via borgmatic "--monitoring-verbosity" flag.
- #290: Reduce the default verbosity of borgmatic logs sent to Healthchecks monitoring hook. Now, it's warnings and errors only. You can increase the verbosity via the "--monitoring-verbosity" flag.

The Healthchecks monitoring under 1.4.21 is very chatty, the above quietens this down significantly.

- #284: Backup to a removable drive or intermittent server via "soft failure" feature. 

Happy to submit a PR if necessary.

**Comment by b3vis** [comment]
Hi there, apologies for the super late reply... IRL responsibilities take up 99.5% of my free time 👎 

I have just merged a big PR that restructures the images to add SMTP capability and ntfy for smartphone push notifications (check them out!)

I have also upped Borg to 1.5.1 👍
