### ISSUE TITLE
Remove ~/.borgmatic from volume mappings?

### ISSUE THREAD

**Issue by witten** [b3vis/docker-borgmatic#55]
Given that recent versions of borgmatic no longer actually write database dumps to file in `~/.borgmatic`, and only stream to named pipes in that directory, you probably no longer need to map the directory to the host.

Some related discussion here: https://www.reddit.com/r/BorgBackup/comments/jsklol/borg_backups_hang_and_dont_complete/

**Comment by b3vis** [comment]
Hi @witten, thank you for informing me of the issue. I've created a PR which I'm happy to merge just wanted some feedback if possible

**Comment by witten** [comment]
I merged it! I hope that's okay. And thank you!

**Comment by b3vis** [comment]
Not a problem at all, I am just about to do the version bump for borgmatic to 1.5.12 and release 👍
