### ISSUE TITLE
Add Curl to docker container?

### ISSUE THREAD

**Issue by Sdub76** [b3vis/docker-borgmatic#58]
I need the ability to start/top docker containers using the borgmatic pre- and post- hooks.

The plan is to use "HA dockermon"  from within the borgmatic container. Would you mind adding curl to the docker container for me? Then, I couls be able to stop any container via:

curl -v -X POST <ha_dockermon_ip>:8126/container/container_name --header 'content-type: application/octet-stream' --data '{"state": "stop"}'

**Comment by MarkJonas** [comment]
Wouldn't it also stop the container if you would kill *crond* and thus exit the entrypoint?

**Comment by Sdub76** [comment]
I would use this curl command to stop another Docker, not the Borgmatic Docker. 

The situation is that I don't want to backup a running SQLite database running in another Docker, as it might be corrupted. The safe thing to do is to stop it, backup, then restart it.

**Comment by b3vis** [comment]
Can't see a problem with adding curl to the base image, either submit a PR or I can get around to it this weekend.

Thanks,
b3vis

**Comment by toastie89** [comment]
> I would use this curl command to stop another Docker, not the Borgmatic Docker.
The container includes wget, would it be sufficient?
It would be great to keep the image small as most users will not need curl.

**Comment by b3vis** [comment]
Done: https://github.com/b3vis/docker-borgmatic/releases/tag/v1.1.14-1.5.12

Will issue rebuild commands to docker hub using the same tag because borg and borgmatic haven't received any updates yet
