### ISSUE TITLE
Using a pure-python msgpack! This will result in lower performance.

### ISSUE THREAD

**Issue by MarkJonas** [b3vis/docker-borgmatic#6]
When looking at the borgmatic output I noticed a borg backup warning message:
```
Using a pure-python msgpack! This will result in lower performance.
```

The message can be reproduced with the following borg command:
```
/ # borg prune --dry-run --keep-within 10y /repository                                                         
Using a pure-python msgpack! This will result in lower performance.                                            
/ #
```

I am using the b3vis/borgmatic Docker Hub image bhxxxelj3bkkunf6nhu6p5f (2018-01-27T18:20:04.370Z) which contains borg 1.1.4.

**Comment by b3vis** [comment]
Hi,

Good spot, this one had my scratching my head. Researching the issue there isn't much surrounding the topic other than similar GitHub issues where the slow msg pack error is brought up but not explicitly dealt with. I found a comment saying that it could be the msg pack isn't able to compile correctly so I tried installing the `alpine-sdk` and then using pip to install borg and borgmatic and this solved the issue.

I've pushed commit  [914a550](https://github.com/b3vis/docker-borgmatic/commit/914a550d6d19dcf4d7e9c1771c6f6813adfff269) to fix this

**Comment by MarkJonas** [comment]
Thank you very much for the quick fix. I tested it and the message is gone. :1st_place_medal: 

Performance wise the time for an backup run with close to nothing to do seems to be the same as before. But it is hard to tell because the time it takes jitters between 2 minutes 30 seconds and 4 minutes 50 seconds.

**Comment by b3vis** [comment]
No worries! I love giving back to the community :)

I’ve never really thought about testing the performance from my own experience there can be a few differing factors. If it’s to a remote machine via SSH do you have borgbackup installed on the destination etc. Also if you have the repository checks enabled in your borgmatic yaml that can add time to a job run.

Kind regards 
b3vis
