### ISSUE TITLE
Point to a remote repo?

### ISSUE THREAD

**Issue by stin7** [b3vis/docker-borgmatic#66]
Hi, can we add an example on how to point to a remote repo? Looking at the .env and compose files it looks like the target folder is a mapped volume. Instead, I'd like to configure the source with something like `borg create --progress --stats username@remote.host.address:/destination/folder::backup-name /folder/to/back/up`

I see ways to map SSH keys and I saw issue #1 , so it seems like I'm just missing something obvious. If there was an example to show where to put `username@remote.host.address:/destination/folder::backup-name` that would be very helpful.

Thanks!

**Comment by stin7** [comment]
Looking at https://github.com/witten/borgmatic, perhaps it is as simple as just replacing 

`/mnt/borg-repository` with `username@remote.host.address:/destination/folder::backup-name` in [config.yaml](https://github.com/b3vis/docker-borgmatic/blob/master/base/data/borgmatic.d/config.yaml)

I'll try that later today.

**Comment by JenswBE** [comment]
Hi @stin7, I'm using following setup for a remote repo:
1. [config.yaml](https://github.com/JenswBE/ansible/blob/main/templates/kubo/home/_user_/kubo/borgmatic/borgmatic.d/config.yaml)
![image](https://user-images.githubusercontent.com/6514515/117405610-3181f180-af0c-11eb-8183-82798ea187cb.png)
Note: In the `ssh_command`, you can set the private SSH key and optionally change the port as well.
2. [Setup remote repository from Borgmatic](https://github.com/JenswBE/ansible/blob/main/docs/how-to/Setup%20services.md#borgmatic)
![image](https://user-images.githubusercontent.com/6514515/117406069-d4d30680-af0c-11eb-894e-4cb1d723e5a9.png)

Just be aware you'll have to accept the remote SSH host key. So, you can do this as a first step with the command:
```shell
docker exec -it borgmatic sh -c "ssh -p <PORT> <BORG_USER>@<BORG_HOST>"
```
or alternatively you foresee a file in the `.ssh` directory (next to your private SSH key containing the host keys).
![image](https://user-images.githubusercontent.com/6514515/117406582-8e31dc00-af0d-11eb-857c-544143298683.png)
![image](https://user-images.githubusercontent.com/6514515/117406681-adc90480-af0d-11eb-99bd-b5af6df40377.png)

**Comment by stin7** [comment]
Thank you Jens - that is very helpful. I will try this today. I had gotten as far as updating config.yaml repos, but was having issues with the passphrase being required on my main ssh key.

**Comment by stin7** [comment]
This works, I'll just need to make a new key without a passphrase for it to be automatic. Thanks Jens!
