### ISSUE TITLE
Update docker

### ISSUE THREAD

**Issue by hrv231** [b3vis/docker-borgmatic#80]
Hello,

can you update the docker with the latest version of borg and borgmatic.

It seems that we can't run arbitrary commands with version 1.5.12
https://torsion.org/borgmatic/docs/how-to/run-arbitrary-borg-commands/

Thank you

**Comment by b3vis** [comment]
Hi,

I've updated it manually as docker no longer offer automatic builds on non pro accounts;

docker pull b3vis/borgmatic:v1.1.17-1.5.18

Thanks,
b3vis
